[package]
name = "cuboid"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cuboid"
path = "src/main.rs"

[dependencies]
fj = { path = "../../crates/fj" }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
