[package]
name = "release-operator"
version = "0.3.1"
edition = "2021"
publish = false


[dependencies]
anyhow = "1.0.95"
cargo_metadata = "0.19.1"
cmd_lib = "1.9.5"
env_logger = "0.11.6"
log = "0.4.22"
secstr = "0.5.0"
semver = "1.0.24"
serde_json = "1.0.134"
thiserror = "2.0.9"

[dependencies.autolib]
path = "../autolib"

[dependencies.reqwest]
version = "0.12.12"
features = ["blocking"]

[dependencies.clap]
version = "4.5.23"
features = ["std", "derive", "env"]
default-features = false

[dependencies.serde]
version = "1.0.217"
features = ["derive"]
